print("hello there! please add your tasks")
first = input("add your first task: ")
second = input("add your second task: ")
third = input("add your third task")
print("so... here your all works you have: ")
print("1.", first)
print("2.", second)
print("3.", third)
done = int(input("what task did you finish?(1-3): "))
print("great job. here your updated list: ")
print("1.", "(*)" if done == 1 else "(),", first)
print("2.", "(*)" if done == 2 else "()", second)
print("3.", "(*)" if done == 3 else "()", third)